/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-12 06:11:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addrbook_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>주소록:작성화면</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"addrbook.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("				// <![CDATA[\r\n");
      out.write("				var colours=new Array(\"#a6f\", \"#60f\", \"#60f\", \"#a6f\", \"#ccc\"); // colours for top, right, bottom and left borders and background of bubbles\r\n");
      out.write("				var bubbles=66; // maximum number of bubbles on screen\r\n");
      out.write("				var over_or_under=\"over\"; // set to \"over\" for bubbles to always be on top, or \"under\" to allow them to float behind other objects\r\n");
      out.write("\r\n");
      out.write("				/****************************\r\n");
      out.write("				* JavaScript Bubble Cursor  *\r\n");
      out.write("				*(c)2010-13 mf2fm web-design*\r\n");
      out.write("				*  http://www.mf2fm.com/rv  *\r\n");
      out.write("				* DON'T EDIT BELOW THIS BOX *\r\n");
      out.write("				****************************/\r\n");
      out.write("				var x=ox=400;\r\n");
      out.write("				var y=oy=300;\r\n");
      out.write("				var swide=800;\r\n");
      out.write("				var shigh=600;\r\n");
      out.write("				var sleft=sdown=0;\r\n");
      out.write("				var bubb=new Array();\r\n");
      out.write("				var bubbx=new Array();\r\n");
      out.write("				var bubby=new Array();\r\n");
      out.write("				var bubbs=new Array();\r\n");
      out.write("				var sploosh=false;\r\n");
      out.write("\r\n");
      out.write("				function addLoadEvent(funky) {\r\n");
      out.write("					var oldonload=window.onload;\r\n");
      out.write("					if (typeof(oldonload)!='function') window.onload=funky;\r\n");
      out.write("					else window.onload=function() {\r\n");
      out.write("						if (oldonload) oldonload();\r\n");
      out.write("						funky();\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				addLoadEvent(buble);\r\n");
      out.write("\r\n");
      out.write("				function buble() { if (document.getElementById) {\r\n");
      out.write("					var i, rats, div;\r\n");
      out.write("					for (i=0; i<bubbles; i++) {\r\n");
      out.write("						rats=createDiv(\"3px\", \"3px\");\r\n");
      out.write("						rats.style.visibility=\"hidden\";\r\n");
      out.write("					rats.style.zIndex=(over_or_under==\"over\")?\"1001\":\"0\";\r\n");
      out.write("\r\n");
      out.write("						div=createDiv(\"auto\", \"auto\");\r\n");
      out.write("						rats.appendChild(div);\r\n");
      out.write("						div=div.style;\r\n");
      out.write("						div.top=\"1px\";\r\n");
      out.write("						div.left=\"0px\";\r\n");
      out.write("						div.bottom=\"1px\";\r\n");
      out.write("						div.right=\"0px\";\r\n");
      out.write("						div.borderLeft=\"1px solid \"+colours[3];\r\n");
      out.write("						div.borderRight=\"1px solid \"+colours[1];\r\n");
      out.write("\r\n");
      out.write("						div=createDiv(\"auto\", \"auto\");\r\n");
      out.write("						rats.appendChild(div);\r\n");
      out.write("						div=div.style;\r\n");
      out.write("						div.top=\"0px\";\r\n");
      out.write("						div.left=\"1px\";\r\n");
      out.write("						div.right=\"1px\";\r\n");
      out.write("						div.bottom=\"0px\"\r\n");
      out.write("						div.borderTop=\"1px solid \"+colours[0];\r\n");
      out.write("						div.borderBottom=\"1px solid \"+colours[2];\r\n");
      out.write("\r\n");
      out.write("						div=createDiv(\"auto\", \"auto\");\r\n");
      out.write("						rats.appendChild(div);\r\n");
      out.write("						div=div.style;\r\n");
      out.write("						div.left=\"1px\";\r\n");
      out.write("						div.right=\"1px\";\r\n");
      out.write("						div.bottom=\"1px\";\r\n");
      out.write("						div.top=\"1px\";\r\n");
      out.write("						div.backgroundColor=colours[4];\r\n");
      out.write("						if (navigator.appName==\"Microsoft Internet Explorer\") div.filter=\"alpha(opacity=50)\";\r\n");
      out.write("						else div.opacity=0.5;\r\n");
      out.write("						document.body.appendChild(rats);\r\n");
      out.write("						bubb[i]=rats.style;\r\n");
      out.write("					}\r\n");
      out.write("					set_scroll();\r\n");
      out.write("					set_width();\r\n");
      out.write("					bubble();\r\n");
      out.write("				}}\r\n");
      out.write("\r\n");
      out.write("				function bubble() {\r\n");
      out.write("					var c;\r\n");
      out.write("					if (Math.abs(x-ox)>1 || Math.abs(y-oy)>1) {\r\n");
      out.write("						ox=x;\r\n");
      out.write("						oy=y;\r\n");
      out.write("						for (c=0; c<bubbles; c++) if (!bubby[c]) {\r\n");
      out.write("							bubb[c].left=(bubbx[c]=x)+\"px\";\r\n");
      out.write("							bubb[c].top=(bubby[c]=y-3)+\"px\";\r\n");
      out.write("							bubb[c].width=\"3px\";\r\n");
      out.write("							bubb[c].height=\"3px\"\r\n");
      out.write("							bubb[c].visibility=\"visible\";\r\n");
      out.write("							bubbs[c]=3;\r\n");
      out.write("							break;\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("					for (c=0; c<bubbles; c++) if (bubby[c]) update_bubb(c);\r\n");
      out.write("					setTimeout(\"bubble()\", 20);\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				document.onmousedown=splash;\r\n");
      out.write("				document.onmouseup=function(){clearTimeout(sploosh);};\r\n");
      out.write("\r\n");
      out.write("				function splash() {\r\n");
      out.write("					ox=-1;\r\n");
      out.write("					oy=-1;\r\n");
      out.write("					sploosh=setTimeout('splash()', 100);\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				function update_bubb(i) {\r\n");
      out.write("					if (bubby[i]) {\r\n");
      out.write("						bubby[i]-=bubbs[i]/2+i%2;\r\n");
      out.write("						bubbx[i]+=(i%5-2)/5;\r\n");
      out.write("						if (bubby[i]>sdown && bubbx[i]>sleft && bubbx[i]<sleft+swide+bubbs[i]) {\r\n");
      out.write("						if (Math.random()<bubbs[i]/shigh*2 && bubbs[i]++<8) {\r\n");
      out.write("						bubb[i].width=bubbs[i]+\"px\";\r\n");
      out.write("						bubb[i].height=bubbs[i]+\"px\";\r\n");
      out.write("						}\r\n");
      out.write("							bubb[i].top=bubby[i]+\"px\";\r\n");
      out.write("							bubb[i].left=bubbx[i]+\"px\";\r\n");
      out.write("						}\r\n");
      out.write("						else {\r\n");
      out.write("							bubb[i].visibility=\"hidden\";\r\n");
      out.write("							bubby[i]=0;\r\n");
      out.write("							return;\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				document.onmousemove=mouse;\r\n");
      out.write("				function mouse(e) {\r\n");
      out.write("					if (e) {\r\n");
      out.write("						y=e.pageY;\r\n");
      out.write("						x=e.pageX;\r\n");
      out.write("					}\r\n");
      out.write("					else {\r\n");
      out.write("						set_scroll();\r\n");
      out.write("						y=event.y+sdown;\r\n");
      out.write("						x=event.x+sleft;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				window.onresize=set_width;\r\n");
      out.write("				function set_width() {\r\n");
      out.write("					var sw_min=999999;\r\n");
      out.write("					var sh_min=999999;\r\n");
      out.write("					if (document.documentElement && document.documentElement.clientWidth) {\r\n");
      out.write("						if (document.documentElement.clientWidth>0) sw_min=document.documentElement.clientWidth;\r\n");
      out.write("						if (document.documentElement.clientHeight>0) sh_min=document.documentElement.clientHeight;\r\n");
      out.write("					}\r\n");
      out.write("					if (typeof(self.innerWidth)=='number' && self.innerWidth) {\r\n");
      out.write("						if (self.innerWidth>0 && self.innerWidth<sw_min) sw_min=self.innerWidth;\r\n");
      out.write("						if (self.innerHeight>0 && self.innerHeight<sh_min) sh_min=self.innerHeight;\r\n");
      out.write("					}\r\n");
      out.write("					if (document.body.clientWidth) {\r\n");
      out.write("						if (document.body.clientWidth>0 && document.body.clientWidth<sw_min) sw_min=document.body.clientWidth;\r\n");
      out.write("						if (document.body.clientHeight>0 && document.body.clientHeight<sh_min) sh_min=document.body.clientHeight;\r\n");
      out.write("					}\r\n");
      out.write("					if (sw_min==999999 || sh_min==999999) {\r\n");
      out.write("						sw_min=800;\r\n");
      out.write("						sh_min=600;\r\n");
      out.write("					}\r\n");
      out.write("					swide=sw_min;\r\n");
      out.write("					shigh=sh_min;\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				window.onscroll=set_scroll;\r\n");
      out.write("				function set_scroll() {\r\n");
      out.write("					if (typeof(self.pageYOffset)=='number') {\r\n");
      out.write("						sdown=self.pageYOffset;\r\n");
      out.write("						sleft=self.pageXOffset;\r\n");
      out.write("					}\r\n");
      out.write("					else if (document.body && (document.body.scrollTop || document.body.scrollLeft)) {\r\n");
      out.write("						sdown=document.body.scrollTop;\r\n");
      out.write("						sleft=document.body.scrollLeft;\r\n");
      out.write("					}\r\n");
      out.write("					else if (document.documentElement && (document.documentElement.scrollTop || document.documentElement.scrollLeft)) {\r\n");
      out.write("						sleft=document.documentElement.scrollLeft;\r\n");
      out.write("						sdown=document.documentElement.scrollTop;\r\n");
      out.write("					}\r\n");
      out.write("					else {\r\n");
      out.write("						sdown=0;\r\n");
      out.write("						sleft=0;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				function createDiv(height, width) {\r\n");
      out.write("					var div=document.createElement(\"div\");\r\n");
      out.write("					div.style.position=\"absolute\";\r\n");
      out.write("					div.style.height=height;\r\n");
      out.write("					div.style.width=width;\r\n");
      out.write("					div.style.overflow=\"hidden\";\r\n");
      out.write("					div.style.backgroundColor=\"transparent\";\r\n");
      out.write("					return (div);\r\n");
      out.write("				}\r\n");
      out.write("				// ]]>\r\n");
      out.write("				</script>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<H2>주소록:작성화면 </H2>\r\n");
      out.write("<HR>\r\n");
      out.write("[<a href=\"list.do\">주소록 목록으로</a>] <P>\r\n");
      out.write("<form name=form1 method=get action=\"insert.do\">\r\n");
      out.write("<input type=hidden name=\"action\" value=\"insert\">\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>이 름</th>	\r\n");
      out.write("    <td><input type=\"text\" name=\"abName\" maxlength=\"15\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>email</th>\r\n");
      out.write("    <td><input type=\"email\" name=\"abEmail\" maxlength=\"50\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>전화번호</th>\r\n");
      out.write("    <td><input type=\"text\" name=\"abTel\" maxlength=\"20\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>생 일</th>\r\n");
      out.write("    <td><input type=\"date\" name=\"abBirth\"></td>\r\n");
      out.write("  </tr>  \r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>회 사</th>\r\n");
      out.write("    <td><input type=\"text\" name=\"abComdept\" maxlength=\"20\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>메 모</th>\r\n");
      out.write("    <td><input type=\"text\" name=\"abMemo\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=2 align=center><input type=submit value=\"저장\"><input type=reset value=\"취소\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<a href=\"/25-08-09/logout_control.jsp\">logout</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
